name: Deploy to FTP Server

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls the latest code from the repo into the GitHub runner

      # Step 2: Update VERSION.txt with commit info BEFORE uploading to FTP
      - name: Update VERSION.txt
        run: |
          # Write the current commit SHA and branch name to VERSION.txt
          echo "Commit Info: ${{ github.sha }}" > VERSION.txt
          echo "Branch: ${{ github.ref }}" >> VERSION.txt
          
          # Configure Git user info for committing
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Commit and push the updated VERSION.txt back to the repository
          git add VERSION.txt
          git commit -m "Update VERSION.txt with current commit info"
          git push

      # Step 3: Upload project files to the FTP server
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0  # Action that handles FTP uploading
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}     # Your FTP server (stored securely in GitHub secrets)
          ftp-username: ${{ secrets.FTP_USERNAME }} # Your FTP username
          ftp-password: ${{ secrets.FTP_PASSWORD }} # Your FTP password
          local-dir: './'       # Local directory to upload (the current repo)
          remote-dir: '/'       # Remote FTP directory (root)
